-- ============================================================
-- 0114: 기본 운동 카탈로그 확장 (238종)
-- 사용자 요청(2026-10-05): 붙여넣은 299종 중 기존에 없는 것만 추가.
-- 적용: 에이전트가 Supabase MCP로 적용 (비파괴 insert). 0001~0113은 수정 금지.
--
-- 제외 기준 (운영 DB 대조, 2026-10-05)
--   · 이름이 같은 것 48종 (공백만 다른 것 포함: 레그 프레스=레그프레스,
--     체스트 프레스 머신=체스트프레스 머신, 케이블 푸시 다운=케이블 푸시다운,
--     페이스 풀=페이스풀)
--   · 같은 운동의 다른 이름 7종
--       컨벤셔널(바벨) 데드리프트 = 컨벤셔널 데드리프트
--       에어 스쿼트 = 맨몸 스쿼트 / 와이드 에어 스쿼트 = 와이드 스쿼트
--       맨몸 카프 레이즈 = 카프 레이즈 / 맨몸 레터럴 런지 = 사이드 런지
--       맨몸 백워드 런지 = 리버스 런지 / 무릎 푸시업 = 니 푸시업
--   · 사실상 같다고 보고 보류한 6종 (사용자가 원하면 다음 번호로 추가)
--       바벨 힙 쓰러스트(힙 쓰러스트가 이미 weight) · 바벨 업라이트 로우(업라이트 로우)
--       숄더 프레스 머신(숄더프레스) · Y 레이즈(라잉 Y 레이즈)
--       복근 에어 바이크(바이시클 크런치) · 스모 에어 스쿼트(와이드 스쿼트)
--
-- 규칙 (0008·0054와 같다)
--   · body_part는 0004 CHECK(가슴/등/하체/어깨/팔/코어/유산소). '복근'은 '코어'.
--   · measure는 맨몸만 reps/time, 웨이트는 null.
--   · 맨몸/웨이트 구분은 챌린지 실적 집계에 쓰인다 — '중량 ~'은 weight.
--   · created_at을 1ms씩 벌려 붙여넣은 순서를 지킨다. 피커는 사용 횟수가 같으면
--     created_at 순이라, 한 문장에 now()가 같으면 부위 묶음이 흩어질 수 있다.
-- ============================================================

insert into public.exercise_catalog (name, body_part, exercise_type, measure, created_at)
select v.name, v.body_part, v.exercise_type, v.measure::text,
       now() + (row_number() over () * interval '1 millisecond')
from (values
  -- ── 하체 ──
  ('저처 스쿼트', '하체', 'weight', null),
  ('바벨 불가리안 스플릿 스쿼트', '하체', 'weight', null),
  ('덤벨 불가리안 스플릿 스쿼트', '하체', 'weight', null),
  ('덤벨 고블릿 스쿼트', '하체', 'weight', null),
  ('맨몸 스플릿 스쿼트', '하체', 'bodyweight', 'reps'),
  ('덤벨 스플릿 스쿼트', '하체', 'weight', null),
  ('케틀벨 고블릿 스쿼트', '하체', 'weight', null),
  ('스모 데드리프트', '하체', 'weight', null),
  ('스탠딩 카프 레이즈', '하체', 'weight', null),
  ('힙 어덕션 머신', '하체', 'weight', null),
  ('힙 어브덕션 머신', '하체', 'weight', null),
  ('중량 스텝업', '하체', 'weight', null),
  ('브이 스쿼트', '하체', 'weight', null),
  ('리버스 브이 스쿼트', '하체', 'weight', null),
  ('글루트 킥백 머신', '하체', 'weight', null),
  ('시티드 카프 레이즈', '하체', 'weight', null),
  ('정지 백 스쿼트', '하체', 'weight', null),
  ('트랩바 데드리프트', '하체', 'weight', null),
  ('스미스머신 스쿼트', '하체', 'weight', null),
  ('케이블 힙 어브덕션', '하체', 'weight', null),
  ('핵 스쿼트 머신', '하체', 'weight', null),
  ('정지 데드리프트', '하체', 'weight', null),
  ('정지 스모 데드리프트', '하체', 'weight', null),
  ('바벨 박스 스쿼트', '하체', 'weight', null),
  ('바벨 프론트 랙 런지', '하체', 'weight', null),
  ('바벨 점프 스쿼트', '하체', 'weight', null),
  ('바벨 런지', '하체', 'weight', null),
  ('바벨 레터럴 런지', '하체', 'weight', null),
  ('바벨 스플릿 스쿼트', '하체', 'weight', null),
  ('바벨 스탠딩 카프 레이즈', '하체', 'weight', null),
  ('스티프 레그 데드리프트', '하체', 'weight', null),
  ('맨몸 오버헤드 스쿼트', '하체', 'bodyweight', 'reps'),
  ('덤벨 스모 스쿼트', '하체', 'weight', null),
  ('덤벨 레그 컬', '하체', 'weight', null),
  ('덤벨 스쿼트', '하체', 'weight', null),
  ('바벨 핵 스쿼트', '하체', 'weight', null),
  ('시티드 레그 컬', '하체', 'weight', null),
  ('힙 쓰러스트 머신', '하체', 'weight', null),
  ('덤벨 루마니안 데드리프트', '하체', 'weight', null),
  ('라잉 힙 어브덕션', '하체', 'bodyweight', 'reps'),
  ('싱글 레그 글루트 브릿지', '하체', 'bodyweight', 'reps'),
  ('피스톨 박스 스쿼트', '하체', 'bodyweight', 'reps'),
  ('사이드 라잉 클램', '하체', 'bodyweight', 'reps'),
  ('맨몸 원레그 데드리프트', '하체', 'bodyweight', 'reps'),
  ('바벨 원레그 데드리프트', '하체', 'weight', null),
  ('덤벨 원레그 데드리프트', '하체', 'weight', null),
  ('케틀벨 데드리프트', '하체', 'weight', null),
  ('케틀벨 스모 데드리프트', '하체', 'weight', null),
  ('덤벨 스모 데드리프트', '하체', 'weight', null),
  ('덤벨 스티프 레그 데드리프트', '하체', 'weight', null),
  ('덤벨 레터럴 런지', '하체', 'weight', null),
  ('케틀벨 레터럴 런지', '하체', 'weight', null),
  ('원레그 익스텐션', '하체', 'weight', null),
  ('원레그 컬', '하체', 'weight', null),
  ('원레그 프레스', '하체', 'weight', null),
  ('수평 레그 프레스', '하체', 'weight', null),
  ('수평 원레그 프레스', '하체', 'weight', null),
  ('시티드 원레그 컬', '하체', 'weight', null),
  ('노르딕 햄스트링 컬', '하체', 'bodyweight', 'reps'),
  ('바벨 스모 스쿼트', '하체', 'weight', null),
  ('케틀벨 스모 스쿼트', '하체', 'weight', null),
  ('덩키 킥', '하체', 'bodyweight', 'reps'),
  ('케이블 킥백', '하체', 'weight', null),
  ('데피싯 데드리프트', '하체', 'weight', null),
  ('런지 트위스트', '하체', 'bodyweight', 'reps'),
  ('케틀벨 런지 트위스트', '하체', 'weight', null),
  ('케이블 풀 스루', '하체', 'weight', null),
  ('몬스터 글루트 머신', '하체', 'weight', null),
  ('펜듈럼 스쿼트 머신', '하체', 'weight', null),
  ('리니어 핵 스쿼트 머신', '하체', 'weight', null),
  ('스미스머신 카프 레이즈', '하체', 'weight', null),
  ('덤벨 스탠딩 카프 레이즈', '하체', 'weight', null),
  ('바벨 백워드 런지', '하체', 'weight', null),
  ('케틀벨 백워드 런지', '하체', 'weight', null),
  ('스탠딩 햄스트링 컬 머신', '하체', 'weight', null),
  ('글루트 햄 레이즈', '하체', 'bodyweight', 'reps'),
  ('스미스머신 불가리안 스플릿 스쿼트', '하체', 'weight', null),
  ('벨트 스쿼트 머신', '하체', 'weight', null),
  ('세이프티바 스쿼트', '하체', 'weight', null),
  ('스미스머신 힙 쓰러스트', '하체', 'weight', null),
  ('덩키 카프 레이즈', '하체', 'weight', null),
  ('트랩바 스쿼트', '하체', 'weight', null),
  ('덤벨 프론트 스쿼트', '하체', 'weight', null),
  ('보수볼 원레그 데드리프트', '하체', 'bodyweight', 'reps'),
  ('보수볼 덤벨 원레그 데드리프트', '하체', 'weight', null),
  ('레버리지 스쿼트 머신', '하체', 'weight', null),
  ('파이어 하이드런트', '하체', 'bodyweight', 'reps'),
  ('스탠딩 힙 어브덕션', '하체', 'bodyweight', 'reps'),
  ('로터리 카프 머신', '하체', 'weight', null),
  ('케틀벨 원레그 데드리프트', '하체', 'weight', null),
  ('바벨 오버헤드 스쿼트', '하체', 'weight', null),
  ('시시 스쿼트', '하체', 'bodyweight', 'reps'),
  ('중량 시시 스쿼트', '하체', 'weight', null),
  ('스미스머신 핵 스쿼트', '하체', 'weight', null),
  ('덤벨 워킹 런지', '하체', 'weight', null),
  -- ── 어깨 ──
  ('스미스머신 오버헤드 프레스', '어깨', 'weight', null),
  ('스미스머신 슈러그', '어깨', 'weight', null),
  ('벤트오버 덤벨 레터럴 레이즈', '어깨', 'weight', null),
  ('비하인드 넥 프레스', '어깨', 'weight', null),
  ('덤벨 프론트 레이즈', '어깨', 'weight', null),
  ('덤벨 슈러그', '어깨', 'weight', null),
  ('바벨 슈러그', '어깨', 'weight', null),
  ('핸드스탠드 푸시업', '어깨', 'bodyweight', 'reps'),
  ('케이블 리버스 플라이', '어깨', 'weight', null),
  ('덤벨 업라이트 로우', '어깨', 'weight', null),
  ('이지바 업라이트 로우', '어깨', 'weight', null),
  ('푸시 프레스', '어깨', 'weight', null),
  ('리어 델토이드 플라이 머신', '어깨', 'weight', null),
  ('레터럴 레이즈 머신', '어깨', 'weight', null),
  ('케이블 레터럴 레이즈', '어깨', 'weight', null),
  ('케이블 프론트 레이즈', '어깨', 'weight', null),
  ('이지바 프론트 레이즈', '어깨', 'weight', null),
  ('시티드 덤벨 리어 레터럴 레이즈', '어깨', 'weight', null),
  ('숄더 탭', '어깨', 'bodyweight', 'reps'),
  ('시티드 바벨 숄더 프레스', '어깨', 'weight', null),
  ('시티드 덤벨 숄더 프레스', '어깨', 'weight', null),
  ('플레이트 숄더 프레스', '어깨', 'weight', null),
  ('덤벨 Y 레이즈', '어깨', 'weight', null),
  ('슈러그 머신', '어깨', 'weight', null),
  ('케이블 슈러그', '어깨', 'weight', null),
  ('케이블 인터널 로테이션', '어깨', 'weight', null),
  ('케이블 익스터널 로테이션', '어깨', 'weight', null),
  ('원암 케이블 레터럴 레이즈', '어깨', 'weight', null),
  ('랜드마인 프레스', '어깨', 'weight', null),
  ('원암 랜드마인 프레스', '어깨', 'weight', null),
  -- ── 가슴 ──
  ('스미스머신 벤치프레스', '가슴', 'weight', null),
  ('스미스머신 인클라인 벤치프레스', '가슴', 'weight', null),
  ('인클라인 덤벨 벤치프레스', '가슴', 'weight', null),
  ('스탠딩 케이블 플라이', '가슴', 'weight', null),
  ('중량 딥스', '가슴', 'weight', null),
  ('인클라인 덤벨 플라이', '가슴', 'weight', null),
  ('중량 푸시업', '가슴', 'weight', null),
  ('힌두 푸시업', '가슴', 'bodyweight', 'reps'),
  ('아처 푸시업', '가슴', 'bodyweight', 'reps'),
  ('클로즈그립 푸시업', '가슴', 'bodyweight', 'reps'),
  ('펙덱 플라이 머신', '가슴', 'weight', null),
  ('인클라인 벤치프레스 머신', '가슴', 'weight', null),
  ('덤벨 풀오버', '가슴', 'weight', null),
  ('시티드 딥스 머신', '가슴', 'weight', null),
  ('로우 풀리 케이블 플라이', '가슴', 'weight', null),
  ('해머 벤치프레스', '가슴', 'weight', null),
  ('스포토 벤치프레스', '가슴', 'weight', null),
  ('어시스트 딥스 머신', '가슴', 'weight', null),
  ('디클라인 벤치프레스', '가슴', 'weight', null),
  ('바벨 플로어 프레스', '가슴', 'weight', null),
  ('클랩 푸시업', '가슴', 'bodyweight', 'reps'),
  ('디클라인 덤벨 플라이', '가슴', 'weight', null),
  ('디클라인 푸시업', '가슴', 'bodyweight', 'reps'),
  ('인클라인 푸시업', '가슴', 'bodyweight', 'reps'),
  ('디클라인 체스트 프레스 머신', '가슴', 'weight', null),
  ('인클라인 덤벨 트위스트 프레스', '가슴', 'weight', null),
  ('인클라인 케이블 플라이', '가슴', 'weight', null),
  ('덤벨 스퀴즈 프레스', '가슴', 'weight', null),
  -- ── 팔 ──
  ('이지바 컬', '팔', 'weight', null),
  ('클로즈 그립 벤치프레스', '팔', 'weight', null),
  ('시티드 덤벨 트라이셉 익스텐션', '팔', 'weight', null),
  ('덤벨 킥백', '팔', 'weight', null),
  ('이지바 리스트 컬', '팔', 'weight', null),
  ('덤벨 리스트 컬', '팔', 'weight', null),
  ('스컬 크러셔', '팔', 'weight', null),
  ('바벨 라잉 트라이셉 익스텐션', '팔', 'weight', null),
  ('덤벨 프리쳐 컬', '팔', 'weight', null),
  ('바벨 프리쳐 컬', '팔', 'weight', null),
  ('이지바 프리쳐 컬', '팔', 'weight', null),
  ('프리쳐 컬 머신', '팔', 'weight', null),
  ('암 컬 머신', '팔', 'weight', null),
  ('케이블 해머컬', '팔', 'weight', null),
  ('케이블 오버헤드 트라이셉 익스텐션', '팔', 'weight', null),
  ('케이블 라잉 트라이셉 익스텐션', '팔', 'weight', null),
  ('리버스 바벨 리스트 컬', '팔', 'weight', null),
  ('리버스 덤벨 리스트 컬', '팔', 'weight', null),
  ('인클라인 덤벨 컬', '팔', 'weight', null),
  ('리스트 롤러', '팔', 'weight', null),
  ('리버스 바벨 컬', '팔', 'weight', null),
  ('트라이셉 익스텐션 머신', '팔', 'weight', null),
  ('악력기', '팔', 'weight', null),
  ('케이블 로프 푸시 다운', '팔', 'weight', null),
  ('컨센트레이션 컬', '팔', 'weight', null),
  ('바벨 JM 프레스', '팔', 'weight', null),
  ('스미스머신 JM 프레스', '팔', 'weight', null),
  ('리버스 이지바 컬', '팔', 'weight', null),
  ('리버스그립 푸시업', '팔', 'bodyweight', 'reps'),
  ('이지바 트라이셉 익스텐션', '팔', 'weight', null),
  ('클로즈그립 스미스머신 벤치프레스', '팔', 'weight', null),
  ('이지바 비하인드 백 리스트 컬', '팔', 'weight', null),
  ('원암 덤벨 리스트 컬', '팔', 'weight', null),
  ('덤벨 라잉 트라이셉 익스텐션', '팔', 'weight', null),
  ('이지바 라잉 트라이셉 익스텐션', '팔', 'weight', null),
  ('인클라인 덤벨 해머 컬', '팔', 'weight', null),
  ('덤벨 스컬 크러셔', '팔', 'weight', null),
  ('시티드 바벨 트라이셉 익스텐션', '팔', 'weight', null),
  ('바이셉 컬 머신', '팔', 'weight', null),
  ('비하인드 백 리스트 컬', '팔', 'weight', null),
  ('트라이셉 프레스 머신', '팔', 'weight', null),
  ('원암 덤벨 컬', '팔', 'weight', null),
  ('원암 덤벨 해머 컬', '팔', 'weight', null),
  ('리버스 이지바 리스트 컬', '팔', 'weight', null),
  ('덤벨 리스트 수피네이션', '팔', 'weight', null),
  ('덤벨 리스트 라디얼 플렉션', '팔', 'weight', null),
  ('케이블 스트레치 컬', '팔', 'weight', null),
  ('케이블 크로스 트라이셉 익스텐션', '팔', 'weight', null),
  ('덤벨 스파이더 컬', '팔', 'weight', null),
  ('이지바 스파이더 컬', '팔', 'weight', null),
  ('케이블 이지바 푸시 다운', '팔', 'weight', null),
  ('리버스 덤벨 컬', '팔', 'weight', null),
  ('시티드 덤벨 해머 컬', '팔', 'weight', null),
  ('시티드 덤벨 컬', '팔', 'weight', null),
  ('덤벨 프리처 해머 컬', '팔', 'weight', null),
  ('덤벨 인클라인 킥백', '팔', 'weight', null),
  ('바벨 스파이더 컬', '팔', 'weight', null),
  -- ── 코어 (붙여넣은 목록의 '복근') ──
  ('행잉 레그 레이즈', '코어', 'bodyweight', 'reps'),
  ('할로우 락', '코어', 'bodyweight', 'reps'),
  ('할로우 포지션', '코어', 'bodyweight', 'time'),
  ('덤벨 사이드 벤드', '코어', 'weight', null),
  ('토즈투 바', '코어', 'bodyweight', 'reps'),
  ('행잉 니 레이즈', '코어', 'bodyweight', 'reps'),
  ('복근 크런치 머신', '코어', 'weight', null),
  ('케이블 크런치', '코어', 'weight', null),
  ('필라테스 잭나이프', '코어', 'bodyweight', 'reps'),
  ('리버스 크런치', '코어', 'bodyweight', 'reps'),
  ('45도 사이드 벤드', '코어', 'weight', null),
  ('RKC 플랭크', '코어', 'bodyweight', 'time'),
  ('케이블 사이드 벤드', '코어', 'weight', null),
  ('디클라인 크런치', '코어', 'bodyweight', 'reps'),
  ('중량 디클라인 크런치', '코어', 'weight', null),
  ('디클라인 리버스 크런치', '코어', 'bodyweight', 'reps'),
  ('디클라인 싯업', '코어', 'bodyweight', 'reps'),
  ('중량 디클라인 싯업', '코어', 'weight', null),
  ('사이드 크런치', '코어', 'bodyweight', 'reps'),
  ('케이블 트위스트', '코어', 'weight', null),
  ('업도미널 힙 쓰러스트', '코어', 'bodyweight', 'reps'),
  ('중량 업도미널 힙 쓰러스트', '코어', 'weight', null),
  ('토르소 로테이션 머신', '코어', 'weight', null),
  ('시티드 니업', '코어', 'bodyweight', 'reps'),
  ('복근 코스터 머신', '코어', 'weight', null),
  ('플랭크 트위스트', '코어', 'bodyweight', 'reps'),
  ('캡틴스 체어 니 레이즈', '코어', 'bodyweight', 'reps'),
  ('캣 카우 스트레치', '코어', 'bodyweight', 'reps')
) as v(name, body_part, exercise_type, measure)
on conflict (name) where created_by is null do nothing;
